[env]
TERM = "xterm-256color"
SHELL = "/bin/bash"
LANG = "en_US.UTF-8"

[shell]
program = "/bin/bash"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

option_as_alt = "Both"

startup_mode = "Fullscreen"

[font]
normal.family = "JetBrainsMono Nerd Font"

size = 20
